# Generated by Django 6.0.2 on 2026-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_submission_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Checked', 'Checked')], default='Submitted', max_length=20),
        ),
    ]
