# Generated by Django 6.0.2 on 2026-02-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_submission_marks_alter_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
