# Generated by Django 6.0.2 on 2026-02-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='semester',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
