# Generated by Django 6.0.2 on 2026-02-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_assignment_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=20),
        ),
    ]
