# Generated by Django 6.0.2 on 2026-03-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_assignment_semester_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
