# Generated by Django 6.0.2 on 2026-03-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_assignment_file_alter_submission_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='department',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Commerce', 'Commerce'), ('History', 'History'), ('Economics', 'Economics'), ('Computer Science', 'Computer Science'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Botany', 'Botany'), ('BCA', 'BCA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Commerce', 'Commerce'), ('History', 'History'), ('Economics', 'Economics'), ('Computer Science', 'Computer Science'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Botany', 'Botany'), ('BCA', 'BCA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4'), ('Semester 5', 'Semester 5'), ('Semester 6', 'Semester 6')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year')]),
        ),
    ]
