# Generated by Django 6.0.2 on 2026-03-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_student_options_alter_submission_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(default=1, upload_to='submissions/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Checked', 'Checked')], default='Submitted', max_length=20),
        ),
    ]
