# Generated by Django 6.0.2 on 2026-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_student_password_alter_teacher_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='regno',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('Tamil', 'Tamil'), ('English', 'English'), ('Commerce', 'Commerce'), ('History', 'History'), ('Economics', 'Economics'), ('Computer Science', 'Computer Science'), ('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Zoology', 'Zoology'), ('Botany', 'Botany'), ('BCA', 'BCA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='empid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
